# Generated by Django 2.1.7 on 2019-04-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='null', max_length=200)),
                ('Type', models.CharField(default='null', max_length=200)),
                ('class_related', models.CharField(default='null', max_length=200)),
                ('location', models.CharField(default='null', max_length=200)),
                ('duration', models.CharField(default='null', max_length=200)),
                ('start', models.CharField(default='null', max_length=200)),
                ('end', models.CharField(default='null', max_length=200)),
                ('description', models.CharField(default='null', max_length=200)),
                ('makeup', models.CharField(default='null', max_length=200)),
                ('assigned_Professors', models.CharField(default='null', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='Cohort_Size',
        ),
        migrations.RemoveField(
            model_name='module',
            name='Enrolment_Size',
        ),
        migrations.RemoveField(
            model_name='module',
            name='assigned_Professors',
        ),
        migrations.RemoveField(
            model_name='module',
            name='class_related',
        ),
        migrations.RemoveField(
            model_name='module',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='module',
            name='course_Lead',
        ),
        migrations.RemoveField(
            model_name='module',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='module',
            name='location',
        ),
        migrations.RemoveField(
            model_name='module',
            name='makeup',
        ),
        migrations.RemoveField(
            model_name='module',
            name='name',
        ),
        migrations.RemoveField(
            model_name='module',
            name='others',
        ),
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='cohort_size',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='cohorts_per_week',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='core',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='enrolment_size',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='labs_per_week',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='lectures_per_week',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='subject_lead',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='term',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Module'),
        ),
    ]
